### PR TITLE
Implemented twitter follow

### PR DESCRIPTION
**Pull request by fronbasal**
Hello,
I implemented the `!follow @HANDLE` command. It takes the user handle as an argument.

### CODE REVIEW

**Comment by fronbasal** [comment]
I also refactored the code, so that `golint` is now (almost completely) happy.

**Comment by fronbasal** [comment]
Any updates @nmeum? 💯

**Comment by nmeum** [comment]
Hey, I merged your `followCmd` function but I didn't like some of the other changes you made and therefore removed them. The commit merging this function is 04e821ae53b45999824116461ea7c81d2edfa340, however, since this is only a mirror it will take some time until it shows up on GitHub.

Anyways, thanks for the pull requests and sorry it took so long 😅

**Comment by fronbasal** [comment]
No problem 👍 
Have fun c:

**Pull request closed without merging**
